___

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" alt="Rossum"></p>

In this assignment you will start off with Numpy Exercises and then complete the whole Exercise with Pandas questions. All the subjects related to questions here already covered in preclass materials and in-class sessions. So good luck!


#### 1. Import NumPy Library

In [1]:
import numpy as np

#### 2. Create an array from my_list=[5,10,15,20,25]

In [3]:
my_list = [5,10,15,20,25]
np.array(my_list)

array([ 5, 10, 15, 20, 25])

#### 3. Generate an array 5x5 zeros 

In [6]:
np.zeros([5,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

#### 4. Generate an array 4x4 ones assign data type int

In [10]:
array1 = np.ones([4,4], dtype = int)
array1

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

#### 5. Make all the values of the array above 7

In [19]:
#array1[array1 == 1] = 7
array1[:,:]=7
array1

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

#### 6. Create same array above with full method

In [24]:
array2 = np.full([4,4], 7)


In [23]:
array2

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

#### 7. Create an array of even integers from 2 to 16 

In [30]:
array7 = np.array(np.arange(2,18,2))
array7

array([ 2,  4,  6,  8, 10, 12, 14, 16])

#### 8. Create a 5x5 matrix with values between 0 to 25

In [37]:
array8 = np.array( np.arange(0,25))
reshaped_array = array8.reshape(5,5)
reshaped_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### 9. Create a 5x5 matrix with values between 0 to 25 using linspace

In [45]:
array9 = np.linspace(0,25,25,dtype = int)
reshaped_array9 = array9.reshape(5,5)
reshaped_array9

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 25]])

#### 10. Create 5 random number with numpy

In [48]:
np.random.random(5)

array([0.06840251, 0.49278411, 0.73917609, 0.47750506, 0.88448262])

#### 11. Create random normal distributed 5x5 array

In [52]:
array_11 = np.random.randn(25).reshape(5,5)
array_11

array([[-0.19445658,  0.45144271,  0.05669791, -1.39086591, -0.27288091],
       [ 1.68043078, -1.6680372 ,  0.11407397, -0.71553046, -1.3599236 ],
       [-1.82449025,  0.58543203, -1.22960266, -0.65917766, -1.63384773],
       [ 0.14881485, -0.40004603, -0.57893804,  1.76119014, -0.65630673],
       [-0.06783475, -1.41614462,  0.40078395,  0.310695  , -1.16123178]])

#### 12. Create 3x4 shaped array with random int numbers between 20 and 50 with numpy

In [101]:
array12 = np.random.randint(20,50, size = (3,4))
array12

array([[43, 48, 48, 29],
       [41, 45, 43, 43],
       [40, 47, 21, 33]])

#### 13. Reshape the array below with shape 6x8

In [56]:
ranarr = np.random.randint(0,52,48)

In [58]:
ranarr = ranarr.reshape(6,8)

In [59]:
ranarr

array([[17, 36, 20,  3, 34,  3, 18, 27],
       [32,  9, 42, 51, 48,  9, 42,  4],
       [48, 48, 16, 18,  7, 33, 50, 28],
       [38, 13, 31, 18, 29, 15, 13, 24],
       [27,  9, 38, 34, 49, 51,  6, 13],
       [ 7, 29, 36, 15, 16, 36, 11, 18]])

In [60]:
#reshape with -1
ranarr.reshape(-1,12)

array([[17, 36, 20,  3, 34,  3, 18, 27, 32,  9, 42, 51],
       [48,  9, 42,  4, 48, 48, 16, 18,  7, 33, 50, 28],
       [38, 13, 31, 18, 29, 15, 13, 24, 27,  9, 38, 34],
       [49, 51,  6, 13,  7, 29, 36, 15, 16, 36, 11, 18]])

## Numpy Indexing and Selection


In [70]:
#Create array below
mat= np.arange(1,17).reshape(4,4)
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

#### 14. Write code that reproduces the output shown below.<br>

In [64]:
mat[1:3, 1:3]

array([[ 6,  7],
       [10, 11]])

#### 15. Get the first column of the array.

In [123]:
mat[:, 0:1]

array([[ 1],
       [ 5],
       [ 9],
       [13]])

#### 16. Get the values in 2nd row for every 2 step.

In [73]:
mat[1:2, 0::2]

array([[5, 7]])

#### 17.Assign 77 to every cell in 3rd column.

In [67]:
mat[:, 2:3]=77

In [30]:

mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

#### 18. Take 2nd row 1st column, 4th row 2nd column.

In [141]:
mat[[1,3],[0,1]]

array([ 5, 14])

#### 19. Take between 2nd and last row with step 2 and between 1 and last column with step 2.

In [130]:
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [139]:
mat[1::2, 0::2]

array([[ 5,  7],
       [13, 15]])

## NumPy Operations

#### 20. Get the sum of values smaller than 10 and values bigger than 12 from array above 

In [112]:
mat[(mat<10) | (mat>12)].sum()

103

In [143]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [144]:
np.array([77,77,77,13,14,77,16])

array([77, 77, 77, 13, 14, 77, 16])

In [145]:
np.array([78,79,81,18,20,85,25])

array([78, 79, 81, 18, 20, 85, 25])

#### 21. Get the standard deviation of the result above

In [148]:
np.std(np.array([78,79,81,18,20,85,25]))

29.700546274093877

#### 22. Get the sum of second column from array above

In [38]:
#print array here
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [120]:
mat[:, 1:2].sum()

32

#### 23. Get the median,mean and std of 3rd row from array above

In [121]:
mat[2]

array([ 9, 10, 11, 12])

In [113]:
mat[2].mean()

10.5

In [115]:
#median
np.median(mat[2])

10.5

In [116]:
#mean
mat[2].mean()

10.5

In [117]:
#std
np.std(mat[2])

1.118033988749895

# Pandas Section

In [80]:
import pandas as pd

**Read Salaries.csv take a look at first 5 rows, df info and df statistical measurements**

In [83]:
sal=pd.read_csv('Salaries.csv')

In [84]:
sal.head()

Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43   
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28   
2  212739.13    106088.18   16452.60       NaN  335279.91         335279.91   
3   77916.00     56120.71  198306.90       NaN  332343.61         332343.61   
4  134401.60      9737.00  182234.59       NaN  326373.19         326373.19   

   Year  Notes         Agency  Status  
0  2011    NaN  San Francisco     NaN  
1  2011    NaN  San Francisco     NaN  
2  2011    NaN  San Francisco     NaN  
3  2011    NaN  San Francisco     NaN  
4  2011    NaN  San Francisco     NaN

In [85]:
sal.describe()

Id        BasePay    OvertimePay       OtherPay  \
count  148654.000000  148045.000000  148650.000000  148650.000000   
mean    74327.500000   66325.448841    5066.059886    3648.767297   
std     42912.857795   42764.635495   11454.380559    8056.601866   
min         1.000000    -166.010000      -0.010000   -7058.590000   
25%     37164.250000   33588.200000       0.000000       0.000000   
50%     74327.500000   65007.450000       0.000000     811.270000   
75%    111490.750000   94691.050000    4658.175000    4236.065000   
max    148654.000000  319275.010000  245131.880000  400184.250000   

            Benefits       TotalPay  TotalPayBenefits           Year  Notes  \
count  112491.000000  148654.000000     148654.000000  148654.000000    0.0   
mean    25007.893151   74768.321972      93692.554811    2012.522643    NaN   
std     15402.215858   50517.005274      62793.533483       1.117538    NaN   
min       -33.890000    -618.130000       -618.130000    2011.000000    NaN   
25%     11535.395000   36168.995000      44065.650000    2012.000000    NaN   
50%     28628.620000   71426.610000      92404.090000    2013.000000    NaN   
75%     35566.855000  105839.135000     132876.450000    2014.000000    NaN   
max     96570.660000  567595.430000     567595.430000    2014.000000    NaN   

       Status  
count     0.0  
mean      NaN  
std       NaN  
min       NaN  
25%       NaN  
50%       NaN  
75%       NaN  
max       NaN

**How many different year value are there**

In [159]:
sal.groupby('Year')['Id'].count()

Year
2011    36159
2012    36766
2013    37606
2014    38123
Name: Id, dtype: int64

**Print out max and avg Totalpay**

In [165]:
#max
print( f"The maximum totalpaymet is {sal['TotalPay'].max()}")

The maximum totalpaymet is 567595.43


In [166]:
#avg

print( f"The maximum totalpaymet is {sal['TotalPay'].mean()}")

The maximum totalpaymet is 74768.321971703


**How many records are there which have TotalPay bigger than avg TotalPay**

In [173]:
sal['Id'][sal['TotalPay']> sal['TotalPay'].mean()].count()

69489

**How much does ALBERT PARDINI make (including benefits)?**

In [175]:
sal['TotalPay'][sal['EmployeeName'] == "ALBERT PARDINI"] + sal['TotalPayBenefits'][sal['EmployeeName'] == "ALBERT PARDINI"]

2    670559.82
dtype: float64

**Who is lowest paid person**

In [178]:
sal['EmployeeName'][sal['TotalPay'] == sal['TotalPay'].min()]

148653    Joe Lopez
Name: EmployeeName, dtype: object

**What are the unique Jobs in dataset?**

In [179]:
sal['JobTitle'].unique()

array(['GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY',
       'CAPTAIN III (POLICE DEPARTMENT)',
       'WIRE ROPE CABLE MAINTENANCE MECHANIC', ..., 'Conversion',
       'Cashier 3', 'Not provided'], dtype=object)

**List 3 least common Jobs**

In [192]:
sal.groupby('JobTitle').Id.count().sort_values()[0:3]

JobTitle
ZOO CURATOR                               1
DIRECTOR, INFORMATION TECHNOLOGY GROUP    1
DIRECTOR, HUMAN RESOURCES                 1
Name: Id, dtype: int64

**How many people earned more than avg in 2012**

In [203]:
#sal['Id'][(sal['Year'] == 2012) & (sal['TotalPay']> sal['TotalPay'].mean())].count()
sal.groupby('Year')[]

**How many people have the word Manager in their job title?**

In [218]:
#use apply function here

def find_word_within_string(the_string, word):
    return word in the_string.lower()

sal['Is_Manager'] = sal['JobTitle'].apply(find_word_within_string, word = 'manager')
sal['Is_Manager'][sal['Is_Manager']== True].count()



4110

**Take Id,EmployeeName,JobTitle,TotalPay and TotalPayBenefits columns with iloc and assign it as sal_new dataframe**

In [227]:
sal.head()

Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43   
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28   
2  212739.13    106088.18   16452.60       NaN  335279.91         335279.91   
3   77916.00     56120.71  198306.90       NaN  332343.61         332343.61   
4  134401.60      9737.00  182234.59       NaN  326373.19         326373.19   

   Year  Notes         Agency  Status  Is_Manager  
0  2011    NaN  San Francisco     NaN        True  
1  2011    NaN  San Francisco     NaN       False  
2  2011    NaN  San Francisco     NaN       False  
3  2011    NaN  San Francisco     NaN       False  
4  2011    NaN  San Francisco     NaN       False

In [228]:
sal_new = sal.iloc[: , [0,1,2,7,8]]
sal_new

Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
148649  148650      Roy I Tillery   
148650  148651       Not provided   
148651  148652       Not provided   
148652  148653       Not provided   
148653  148654          Joe Lopez   

                                              JobTitle   TotalPay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  567595.43   
1                      CAPTAIN III (POLICE DEPARTMENT)  538909.28   
2                      CAPTAIN III (POLICE DEPARTMENT)  335279.91   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC  332343.61   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  326373.19   
...                                                ...        ...   
148649                                       Custodian       0.00   
148650                                    Not provided       0.00   
148651                                    Not provided       0.00   
148652                                    Not provided       0.00   
148653                      Counselor, Log Cabin Ranch    -618.13   

        TotalPayBenefits  
0              567595.43  
1              538909.28  
2              335279.91  
3              332343.61  
4              326373.19  
...                  ...  
148649              0.00  
148650              0.00  
148651              0.00  
148652              0.00  
148653           -618.13  

[148654 rows x 5 columns]

**Take columns betweeen EmployeeName and TotalPayBenefits with loc and assign it o sal_new df**
 

In [229]:
sal_new= sal.loc[:, 'EmployeeName':'TotalPayBenefits']
sal_new

EmployeeName                                        JobTitle  \
0          NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1            GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2          ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3       CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4         PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   
...                   ...                                             ...   
148649      Roy I Tillery                                       Custodian   
148650       Not provided                                    Not provided   
148651       Not provided                                    Not provided   
148652       Not provided                                    Not provided   
148653          Joe Lopez                      Counselor, Log Cabin Ranch   

          BasePay  OvertimePay   OtherPay  Benefits   TotalPay  \
0       167411.18         0.00  400184.25       NaN  567595.43   
1       155966.02    245131.88  137811.38       NaN  538909.28   
2       212739.13    106088.18   16452.60       NaN  335279.91   
3        77916.00     56120.71  198306.90       NaN  332343.61   
4       134401.60      9737.00  182234.59       NaN  326373.19   
...           ...          ...        ...       ...        ...   
148649       0.00         0.00       0.00       0.0       0.00   
148650        NaN          NaN        NaN       NaN       0.00   
148651        NaN          NaN        NaN       NaN       0.00   
148652        NaN          NaN        NaN       NaN       0.00   
148653       0.00         0.00    -618.13       0.0    -618.13   

        TotalPayBenefits  
0              567595.43  
1              538909.28  
2              335279.91  
3              332343.61  
4              326373.19  
...                  ...  
148649              0.00  
148650              0.00  
148651              0.00  
148652              0.00  
148653           -618.13  

[148654 rows x 8 columns]

**Print out the names of the employees who earn more than min, but less than avg**

In [234]:
sal['EmployeeName'][(sal['TotalPay']> sal['TotalPay'].min()) & (sal['TotalPay']< sal['TotalPay'].mean())]

15847     TATYANA ROTENBERG
15848           WINSTON HOM
15849          CRAIG RIGLER
15850             WENDY TAN
15851        KENNETH BREWER
                ...        
148648          Leon Walker
148649        Roy I Tillery
148650         Not provided
148651         Not provided
148652         Not provided
Name: EmployeeName, Length: 79164, dtype: object